### ISSUE TITLE
Allow multiple input/output tags

### ISSUE THREAD

**Issue by meichthys** [nextcloud/approval#10]
For some use cases it would be helpful to allow a workflow to be triggered by multiple tags and to apply multiple tags at a time. For example:

I have the following workflows:
1. Route to Everyone
2. Route to Molly
3. Route to Mike

When a a file is tagged `Route to Everyone` I would like the `Route to Everyone` workflow to apply both a `Route to Molly` and a `Route to Mike` tag which could then be used by workflow 2 and 3.

**Comment by eneiluj** [comment]
This would require deep changes in the way workflows are defined.

You could more or less achieve this with #11 and directly requesting to multiple workflows.

**Comment by meichthys** [comment]
Ok, feel free to close this. I think #11 would go a long way in improving the situation.
