### ISSUE TITLE
Allow requesting approval with multiple workflows

### ISSUE THREAD

**Issue by meichthys** [nextcloud/approval#11]
Feature Request.

Currently when requesting approval we can only select a single workflow:
It would be helpful if it was possible to select multiple workflows when requesting approval:

**Comment by eneiluj** [comment]
That would be nice. The server-side part already works with files having multiple pending tags. So it would only require some changes in the UI.

I'll probably do it soon.

**Comment by eneiluj** [comment]
Hey, some good news here. The request button is now displayed as long as there is at least one workflow with which the user can request the file (for which the file is not already pending/approved/rejected). Then the request modal only shows those workflows.

One can now make multiple requests for a file. It will be displayed as pending until it's not tagged as pending for any workflow.
In other words, the state priority (to be displayed in the sidebar) is:
1. pending
2. rejected
3. approved

So:
* If the file is pending for at least one workflow (and maybe approved/rejected for others), it's displayed as pending.
* If it's not pending for any workflow anymore, it needs to be approved by all of them to be displayed as approved. It's displayed as rejected if it's rejected by at least one of'em.

This is available in `v1.0.7-4-nightly`. Could you try it?
Tell me if you need help to install the nightly.

**Comment by meichthys** [comment]
Sure, i can test it out. What's the recommended way to install the nightly?

**Comment by eneiluj** [comment]
You can either download the archive from the appstore and manually replace the app directory or install with this occ command:
```
occ app:update --allow-unstable approval
```
When you want to get back to normal releases, just disable and remove the app from app settings and reinstall it.

**Comment by meichthys** [comment]
Tested and found working 👍
