### ISSUE TITLE
NC28 for non customers ?

### ISSUE THREAD

**Issue by roadrunnerjb** [nextcloud/approval#115]
Hi all,

the readme states:

`This app will be deprecated from Nextcloud 28 onwards. If you are a Nextcloud customer and you rely on this app, please wait with updating to 28 and open a support ticket so we can find a solution for your use-case.`

But what if we are no customer. We are a small ngo and some of our work relays on the approval app. 
Will there be a workaround or another mechanism to keep the fuctonality ?

**Comment by julien-nc** [comment]
By the way, it would be very nice if you could try this PR on NC 28 and give us some feedback on the new UI.

**Comment by nikobe123** [comment]
Dear Julien, we are a small organisation that chose Nextcloud a year ago as out main tool and after a year if migration and capacity building, including design and implementation of approval flows we are finally working on this platform and then i saw the note that this app might be discontinued. I cannot tell you how demotivating this was for our team after all that we have put in. It would be really amazing if you reconsider. We are on NC 27 and will not upgrade until we have found a solution to this problem. Let us know what options we have. thank you! Nikobe

**Comment by julien-nc** [comment]
@nikobe123 The support for NC 28 will be added soon. Check #114. If you want to speed up the process you can try the branch and provide feedback in the PR.

**Comment by julien-nc** [comment]
v1.2.0 for NC 28 is out. We are interested in your feedback.

**Comment by nikobe123** [comment]
> @nikobe123 The support for NC 28 will be added soon. Check #114. If you want to speed up the process you can try the branch and provide feedback in the PR.

Thank you so much Julien! We are not very tech savvy, so i dont understand "try the branch" but we will install 28.0.1 in the next weeks and I will test if the approval still works well.

**Comment by roadrunnerjb** [comment]
> v1.2.0 for NC 28 is out. We are interested in your feedback.

In our test env it looks quite good, we are planning to upgrade to NC28 end of march. I will give you an update.

Thank's so much !

**Comment by joshtrichards** [comment]
Fixed in #114
