### ISSUE TITLE
users, circles and groups are not displayed for wokflow configuration

### ISSUE THREAD

**Issue by OkhamG** [nextcloud/approval#13]
Hi, when creating workflows, the "Who can request approval" and "Who can approve" fields only suggest the current user. Cannot configure another user, group or circle when they are present in the directory and available in the standard file sharing menus.

In order to check the correct operation I put my user name in the two fields "Who can request approval" and "Who can approve", the workflow is working but has no interest because I submit documents to myself !

Thanks for your help, I am using nextcloud 22

Best regards
Taurine

**Comment by zydisney** [comment]
same issue

**Comment by eneiluj** [comment]
Hi, thanks for the bug report.

I can't reproduce this bug. Could you check if you see any related error in the browser console (F12 -> Console tab) and in the network tab?

There should be something about ` https://your.nc.org/ocs/v2.php/core/autocomplete/get`.
I'm interested to see which exact URL is requested and what's the error code/message.

It would also be interesting to look for related errors in nextcloud.log

**Comment by zydisney** [comment]
> https://your.nc.org/ocs/v2.php/core/autocomplete/get
I got these error
```
{ocs: {meta: {status: "failure", statuscode: 404,…}, data: []}}
    ocs: {meta: {status: "failure", statuscode: 404,…}, data: []}
        data: []
        meta: {status: "failure", statuscode: 404,…}
            message: "Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.\n"
            status: "failure"
            statuscode: 404
```

**Comment by AdnanCivic** [comment]
I stumbled upon this too. I think the problem ist not the approval app, but the circles app.
If you remove the parameter shareTypes[]=7 and try accessing the API with curl it works.

There is some work to be done in https://github.com/nextcloud/circles/blob/master/lib/Collaboration/v2/CollaboratorSearchPlugin.php

The search function expects an array but gets null. I didnt probe any further.

I disabled the circles app, then users and groups are searchable.

**Comment by eneiluj** [comment]
@zydisney Thanks for the feedback.
@AdnanCivic Thanks for the information.

I was finally able to reproduce the bug with the latest release of circles.

Let's avoid the circles until the related server side is more robust.
v1.0.6 is out and should avoid the autocomplete crash.
Could someone confirm it works (with the circles app enabled)?

**Comment by OkhamG** [comment]
> 
> 
> @zydisney Thanks for the feedback.
> @AdnanCivic Thanks for the information.
> 
> I was finally able to reproduce the bug with the latest release of circles.
> 
> Let's avoid the circles until the related server side is more robust.
> v1.0.6 is out and should avoid the autocomplete crash.
> Could someone confirm it works (with the circles app enabled)?

Hi @eneiluj 

I confirm it works with the circles app enabled (only acces to users and groups, no circles access which is normal because disabled). 

Best regards

**Comment by eneiluj** [comment]
@OkhamG Thanks for the feedback.

**Comment by OkhamG** [comment]
> 
> 
> @OkhamG Thanks for the feedback.

@**eneiluj** Thanks. Last question: It remains the problem with the circles, I have to open another bug in the circles module (https://github.com/nextcloud/ircles)? 
Best regards
