### ISSUE TITLE
approve/reject buttons in the sidebar are gone 

### ISSUE THREAD

**Issue by nikobe123** [nextcloud/approval#158]
We have updated to NC 28 and i saw the buttons were present in the beta test version but are now gone. 

This makes it reallyy hard to find the file you need to approve once it is closed (since you can only request approval, approve or rehject from the file overview page, as far as i can tell) but if you have 100s of documents in that folder it is really hard to find the doc that you need to request approval for. We need to be able to do this from the open document.

**Comment by julien-nc** [comment]
Hi, it is not possible to inject content in the file details sidebar since NC 28. Maybe I'm not aware of another new way to do so but the previous implementation of this sidebar content has never worked with NC 28.
I'll check what's possible here.

**Comment by nikobe123** [comment]
> Hi, it is not possible to inject content in the file details sidebar since NC 28. Maybe I'm not aware of another new way to do so but the previous implementation of this sidebar content has never worked with NC 28. I'll check what's possible here.

Thank you Julient for getting back to us. We use approvals all day long for many processes and it would be key to be able to approve the open file (then you know you are approving the right one). Once it's closed, you have to doublecheck the name, if file names are similar you can approve any file in the foler accidently. I hope i am explaingin it right. Attached a screenshot of a suggestion of where the approval could be.
![approve](https://github.com/nextcloud/approval/assets/153210618/03bc2355-5365-4732-87f7-6fc9739d2a69)

**Comment by julien-nc** [comment]
It's now merged and released in v1.3.0. Could you try it? What do you think of it?

**Comment by nikobe123** [comment]
> It's now merged and released in v1.3.0. Could you try it? What do you think of it?

Dear Julien, thank you so much, it works well on our test server. The only difference is that the old Approval version would change the approval status in the file overview in real time, whereas the new version updates the status only on a reload. The realtime feature was very nice, would be great to have both : ) Best wishes and thank you for your work!

**Comment by nikobe123** [comment]
> It's now merged and released in v1.3.0. Could you try it? What do you think of it?

Dear Julien, thank you so much, it works well on our test server. The only difference is that the old Approval version would change the approval status in the file overview in real time, whereas the new version updates the status only on a reload (when the approval buttons are clicked from the sidebar). So even if i have a doucment open, approve it and close it, the file overview will not show the approval until i do a reload of the browser. If i do the approval from the file overview page (under the three dots) it changes in realtime. The realtime feature was very nice, would be great to have both : ) Best wishes and thank you for your work!
