### ISSUE TITLE
l10n: No need to translate string without content

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/approval#3]
https://github.com/nextcloud/approval/blob/0c51b49c7657bbdd9c80f8317360ff8deb90ea41/lib/Notification/Notifier.php#L175

This is just a placeholder, or?

**Comment by ldmpub** [comment]
Thanks to have reported the issue here (rather than is Transifex).

**Comment by eneiluj** [comment]
@rakekniven Thanks for reporting this. No need to translate this one indeed :grin:.
