### ISSUE TITLE
l10n: "aka" or "AKA"?

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/approval#5]
Does this relate to the [AKA](https://en.wikipedia.org/wiki/Authentication_and_Key_Agreement) authorization method?

https://github.com/nextcloud/approval/blob/c28a15495454b574a4a4bb8bf9409f20e7a8b4b7/src/components/DocuSignSettings.vue#L26

If so, please correct the text string to:
`Client ID (AKA integration key)`

**Comment by tcitworld** [comment]
Nope, it's https://en.wiktionary.org/wiki/also_known_as (but it seems both `aka` and `AKA` forms are used).

**Comment by Valdnet** [comment]
@tcitworld Thanks for the answer. I wanted to make sure :wink:.
