### ISSUE TITLE
Problems with status 500 after installation

### ISSUE THREAD

**Issue by GiuseppeLateral** [nextcloud/approval#6]
I have an installation of Nextcloud 22 on my domain. This is not in the root but under a subfolder called nextcloud-beta.

I didn't use the makefile because I don't have shell access (and I don't have Linux available on my own machine), so instead I have just run composer install and webpack. Then I have moved the folder of Approval under "apps" of my nextcloud installation and I have enabled it.

Problem:
after I go to a file and click on "share" I get this error
https://www.mydomain.com/nextcloud-beta/index.php/apps/approval/user-requester-rules :1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

This is not the only page it fails to load, it also fails at loading other pages like:
https://www.mydomain.com/nextcloud-beta/index.php/apps/approval/20/state

I also get this error (shown at full screen size):
Failed to check approval status:
Nextcloud

What could I make to solve the problem? Thanks

**Comment by eneiluj** [comment]
Thanks for the bug report.

Could you check if there is any error (related with the approval app) in nextcloud.log? It looks like a crash from the server side.

How did you get the app? From the app settings? From the appstore? Did you clone the repo?
Did you install v1.0.1 or another version?

This app is published in the appstore so you should be able to get it from the app settings. It would be interesting to delete the approval app directory that you created and just "download and install" the app from the app settings.

**Comment by eneiluj** [comment]
Any news about this?

Feel free to reopen if needed.
