### ISSUE TITLE
Approval flow problem

### ISSUE THREAD

**Issue by caresia** [nextcloud/approval#85]
Hi!
When an approved file is modified after the approval, the file should be "not approved" and should reenter the flow.
This seems meaningful for me.
At the moment, the modified file remain "approved", although is different from the approved one.
Is there a solution?
Thank you

**Comment by s-rosenfeld** [comment]
There was a similar question before. There is a solution, but with the help of other applications.

https://github.com/nextcloud/approval/issues/17#issuecomment-1462533492

**Comment by caresia** [comment]
Thank you.
Couldn't get to have lua functioning, but I'm using the internal interpreter.
