### ISSUE TITLE
Fix frontend for NC 28

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/approval#97]
A lot of things have changed in Files in 28. We need to adjust the approval app.
@artonge @skjnldsv Can you give me some hints? :grin: 

* Register a file action. [accept share example](https://github.com/nextcloud/server/blob/06efe9f211f36798d970e57040bf5fb49086cdf6/apps/files_sharing/src/actions/acceptShareAction.ts)
* Is it still possible to register a file plugin like in https://github.com/nextcloud/approval/blob/main/src/filesplugin.js#L360 ? If so, has anything changed in the way we should write plugins? Still have to define a `attach(fileList)` method?
* `OCA.Files.DetailFileInfoView.extend()` does not work anymore. `OCA.Files.DetailFileInfoView` has been removed. How can we insert some content in the files details sidebar?
* Is there any way to change the way a file list item looks like? The approval app used a hack to insert an icon in the corner of the file item icon. This most likely does not work anymore. Inserting an element in the line would be enough. Something similar to what's done to show a file has been shared. 
![image](https://github.com/nextcloud/approval/assets/11291457/f6e2a7e1-e3ff-43b3-b9d4-e45ec630928c)

* Maybe more questions will come along the way.

**Comment by skjnldsv** [comment]
> * Is it still possible to register a file plugin like in [`main`/src/filesplugin.js#L360](https://github.com/nextcloud/approval/blob/main/src/filesplugin.js?rgh-link-date=2023-10-09T10%3A51%3A38Z#L360) ? If so, has anything changed in the way we should write plugins? Still have to define a `attach(fileList)` method?

Not anymore no

> * `OCA.Files.DetailFileInfoView.extend()` does not work anymore. `OCA.Files.DetailFileInfoView` has been removed. How can we insert some content in the files details sidebar?

cc @max-nextcloud for removing the Files scripts :see_no_evil: 


> * Is there any way to change the way a file list item looks like? The approval app used a hack to insert an icon in the corner of the file item icon. This most likely does not work anymore. Inserting an element in the line would be enough. Something similar to what's done to show a file has been shared.
>   ![image](https://user-images.githubusercontent.com/11291457/273563577-f6e2a7e1-e3ff-43b3-b9d4-e45ec630928c.png)

You only have to inline buttons, right? Approve and Reject? That should be enough?
Can you show an example of the "icon in the corner of the file item icon" you're refereeing to?

**Comment by joshtrichards** [comment]
Closed by #114
